version: "3.8"
volumes:
  db:
    driver: local

services:
  postgres:
    image: postgres:16.1
    ports:
      - 5555:5432
    volumes:
      - db:/var/lib/psql
    environment:
      - POSTGRES_DB=translo
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
