volumes:
  db:
    driver: local

services:
  postgres:
    image: postgres:16.4
    ports:
      - 5555:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=translo
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
