FROM node:18

RUN apt-get update && apt-get install -y openssl libssl-dev

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

COPY . .

RUN pnpm install

RUN pnpm exec playwright install
RUN pnpm exec playwright install-deps

RUN pnpm prisma:generate

RUN pnpm run build

CMD ["pnpm", "start"]

