name: Lint Commit Messages
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: (github.actor != 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/') == false)
        name: commitlint
        uses: wagoid/commitlint-github-action@v6
