name: Lint Commit Messages
on:
  pull_request:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!master" # exclude master branch

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: (github.actor != 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/') == false)
        name: commitlint
        uses: wagoid/commitlint-github-action@v6
