name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: squash # o 'merge' o 'rebase' se preferisci un altro metodo
          mergeLabel: automerge # etichetta da aggiungere per triggerare l'auto-merge
          allowMinor: true # permette l'auto-merge per le minor
          allowPatch: true # permette l'auto-merge per le patch
