# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches:
      # - master
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:
#   GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-22.04
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    container:
      image: mcr.microsoft.com/playwright:v1.35.0-jammy

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Docker
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Install dependencies
        run: pnpm install

      - name: Run your tests
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm test:e2e:docker

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Stop Docker containers
        run: docker-compose down
